package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	//driver = new ChromeDriver();
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void testFindAvia() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".l-top_menu .\\_avia > .text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".identity__icon__1E4A- path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".identity__icon__1E4A- path")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".o335")).click();
    driver.findElement(By.cssSelector(".o33573")).click();
    driver.findElement(By.cssSelector(".o33573")).click();
    driver.findElement(By.cssSelector(".o33573")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".o33573"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".o33573")).sendKeys("Москва");
    driver.findElement(By.cssSelector(".o33640")).click();
    driver.findElement(By.cssSelector(".o33640")).sendKeys("Санкт-Петербург");
    driver.findElement(By.cssSelector(".o33662")).click();
    driver.findElement(By.cssSelector(".DayPicker-Week:nth-child(5) > .DayPicker-Day:nth-child(6) .DayPicker-Day-day-number")).click();
    driver.findElement(By.cssSelector(".o33670")).click();
    driver.findElement(By.cssSelector(".o33884")).click();
    driver.findElement(By.cssSelector(".DayPicker-Week:nth-child(4) > .DayPicker-Day:nth-child(4) .DayPicker-Day-day-number")).click();
    driver.findElement(By.cssSelector(".o33692 > .o33707 > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".o33692 > .o33707 > div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".j-offers_title"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testFindBus() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".l-top_menu .\\_bus > .text")).click();
    driver.findElement(By.cssSelector(".c01515")).click();
    driver.findElement(By.cssSelector(".c01515")).sendKeys("Москва");
    {
      WebElement element = driver.findElement(By.cssSelector(".c01522"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".c01560")).click();
    driver.findElement(By.cssSelector(".c01560")).sendKeys("Санкт-Петербург");
    driver.findElement(By.cssSelector(".c01573")).click();
    driver.findElement(By.cssSelector(".c01573")).sendKeys("сегодня");
    driver.findElement(By.cssSelector(".DayPicker-Day--today > span")).click();
    driver.findElement(By.cssSelector(".c01639")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".index__nowrap___1JmzG:nth-child(2)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testFindPrigorod() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".tab_etrain")).click();
    driver.findElement(By.name("st1")).click();
    driver.findElement(By.name("st1")).sendKeys("Москва");
    driver.findElement(By.name("st2")).click();
    driver.findElement(By.name("st2")).sendKeys("Санкт-Петербург");
    driver.findElement(By.cssSelector(".j-search_form:nth-child(4) .date_start:nth-child(4) .input_field:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".button_wrp:nth-child(5) .spinner")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".theme__children__1qxmb"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testFindTrain() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".l-top_menu .\\_train > .text")).click();
    driver.findElement(By.name("schedule_station_from")).click();
    driver.findElement(By.name("schedule_station_from")).sendKeys("Москва");
    driver.findElement(By.cssSelector(".j-station_to .b-input__form__standart")).click();
    driver.findElement(By.name("schedule_station_to")).sendKeys("Санкт-Петербург");
    {
      WebElement element = driver.findElement(By.cssSelector(".reduce"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".j-date_to")).click();
    driver.findElement(By.linkText("24")).click();
    driver.findElement(By.cssSelector(".spinner:nth-child(3)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".t-ttl > span:nth-child(1)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testHeaderLinks2Read() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".l-top_menu .\\_help > .text")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".breadcrumbs_nav:nth-child(1)"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void testHeaderLinksAvia() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_avia > .text")).click();
    assertThat(driver.getTitle(), is("Купить дешевые авиабилеты онлайн. Поиск билетов на самолет от всех авиакомпаний - Туту.Ру"));
    driver.close();
  }
  @Test
  public void testHeaderLinksBus() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_bus > .text")).click();
    assertThat(driver.getTitle(), is("Автобусы — купить билеты онлайн и посмотреть расписание. Цены билетов на автобусы на 2020 г"));
    driver.close();
  }
  @Test
  public void testHeaderLinksPrigorod() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_etrain > .text")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_chapter_nolink > .text"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void testHeaderLinksStory() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".l-top_menu .\\_stories > .text")).click();
    driver.switchTo().window(vars.get("win4157").toString());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".infinite-header-container-inner .infinite-orig-logo > img"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testHeaderLinksTours() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_tours > .text")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_1RG168o___headline"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void testHeaderLinksTrains() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_train > .text")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".j-station_from .b-input__form__standart"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void testHeaderLinksTrips() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1266, 692));
    driver.findElement(By.cssSelector(".l-top_menu .\\_trip > .text")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".fBlXyok___headline"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void testLogin() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".j-link-login")).click();
    driver.findElement(By.cssSelector(".mail_wrapper:nth-child(2) > .b-input__standart")).click();
    driver.findElement(By.cssSelector(".mail_wrapper:nth-child(2) > .b-input__standart")).sendKeys("noskoff2@yandex.ru");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("pXmT4DHwbYQGs6c");
    driver.findElement(By.cssSelector(".button_wrapper:nth-child(5) > .b-button__standart")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".logout"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRegistration() {
    driver.get("https://www.tutu.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Зарегистрироваться")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title:nth-child(2)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".b-input__standart:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".button_wrapper:nth-child(6)")).click();
    driver.findElement(By.name("agree")).click();
    driver.findElement(By.cssSelector(".button_wrapper:nth-child(6) .name")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".registration_success > .title"));
      assert(elements.size() > 0);
    }
  }
}
